# fly.toml app configuration file generated for whiskyindex on 2026-08-17T16:57:03Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'whiskyindex'
primary_region = 'fra'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256

[[restart]]
  policy = 'on-failure'
  processes = ['app']
  retries = 3
